### ISSUE TITLE
How to use these in vanilla 47-1?

### ISSUE THREAD

**Issue by konsumer** [coderofsalvation/pd-puredata-vanilla-patches#1]
It appears that these need lots of other things. for example, when I load `defaultxrs-pd-abstractions/synths/tb303~`, I get this:

```
 mrange 150
... couldn't create
 adsr~ 3 100 0 0
... couldn't create
 analog~
... couldn't create
 analog~
... couldn't create
 blosc~ comparator
... couldn't create
 aline~ 150
... couldn't create
 aline~ 10
... couldn't create
 saw~
... couldn't create
 resofilt~ 3
... couldn't create
 mrange 4
... couldn't create
 mrange 2000
... couldn't create
 mrange 997
... couldn't create
 mrange 1
... couldn't create
 list-idx
... couldn't create
 mrange 4
... couldn't create
```

When I try  `defaultxrs-pd-abstractions/synths/hoover~` I get:

```
 pulse~
... couldn't create
 pulse~
... couldn't create
 pulse~
... couldn't create
 chorus~
... couldn't create
 lb $1 7.21
... couldn't create
```

**Comment by coderofsalvation** [comment]
You're right, I guess the 'defaultxrs-pd-abstractions' was only tested in extended pd.
I will delete them.
Are there more directories which didn't turn out to be vanilla patches?

**Comment by konsumer** [comment]
Bummer. I was hoping I was missing something, that collection looks really cool. I'd be happy to test them all. Maybe instead of deleting stuff, we could just track what extensions they need? With the new "Find externals" menu item, it's pretty easy (for amd64 linux, mac, windows) to add the extended externals, if I knew what the parent external collections are, but then I guess the name "pd-puredata-vanilla-patches" doesn't really make sense. I found `pulse~` in sigpack, but couldn't find the others. I'd be willing to do some research, if this seems useful.

**Comment by konsumer** [comment]
Ah, jut noticed in [readme](https://github.com/coderofsalvation/pd-puredata-vanilla-patches/blob/master/defaultxrs-pd-abstractions/README.md):

> I have only tested these in Pd-extended 0.43.4 on Arch Linux. Since they are just abstractions, they should work on any platform that Pd-extended runs on. I have not tested them on Pd-vanilla, but I doubt they would work since a lot of them depend on objects that are only provided by Pd-extended.

**Comment by coderofsalvation** [comment]
ok removed.
Thank you very much for noticing!

**Comment by konsumer** [comment]
Thank you!

**Comment by konsumer** [comment]
I had a closer look. I think I was too hasty. If you put all the pd files in `defaultxrs-pd-abstractions` in one directory, they do seem to work! I just got `hoover~` working with these all in the same dir:

```
atc~.pd
chorus~.pd
cta~.pd
hoover~.pd
lb.pd
pulse~.pd
```

I bet others in that lib work the same. Maybe they just all need to be in the path? It might be helpful to make a top-level pd-file that has defines for all the paths, then you can play around with it.

**Comment by konsumer** [comment]
I went back to `tb303~`. After installing (in new version of pd-vanilla, under Help/Find Externals)
creb, lib-abs & markex and putting all the `defaultxrs-pd-abstractions` in one dir, it worked.

For these, I had to add the prefix of the lib-name + `/` (eg: `creb/resofilt~`)

### creb
- `resofilt~`
- `blosc~`

### list-abs
- `list-idx`

### markex
- `randomF`

When all were installed, my dir looked like this:

```
adsr~.pd
aline~.pd
analog~.pd
cta~.pd
lb.pd
mrange.pd
saw~.pd
tb303~.pd
```
